POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhwdXJvIiwiaWQiOiI2ODIxZjM0MzJiNjQyMDEzYzJlOWMzOWMiLCJpYXQiOjE3NDcwNTU1ODksImV4cCI6MTc0NzA1OTE4OX0.BlG4w9OzM6iWiAwnQRh2-iD2cVuqlcDMh4RxHhQop8I

{
    "title": "Lukujonossa",
    "author": "Sanna Ruoho",
    "url": "https://lukujonossa.fi/",
    "likes": "1"
}